#!/bin/bash
cd ./application
npm install
cd ./libraries/luca-api-initializer
npm install
cd ./libraries/luca-client-initializer
npm install
cd ./libraries/luca-couchdb-synchronizer
npm install
cd ./libraries/luca-spec-bootstrapper
npm install
cd ./services/categories/api
npm install
cd ./services/checking-account/api
npm install
cd ./services/checking-account/client
npm install
cd ./services/service-registry/api
npm install
cd ./services/service-registry/client
npm install
cd ./services/users/api
npm install
cd ./services/users/client
npm install
